Clientes/Models/Empleado.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Clientes.Models
{
    public class Empleado
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(15)]
        public string Cedula { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        public string Nombres { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        public string Apellidos { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime FechaDeNacimiento { get; set; }

        [StringLength(50)]
        public string Departamento { get; set; } = string.Empty;

        [StringLength(50)]
        public string Municipio { get; set; } = string.Empty;

        [StringLength(200)]
        public string Dirección { get; set; } = string.Empty;

        [StringLength(15)]
        public string Teléfono { get; set; } = string.Empty;

        [StringLength(15)]
        public string Celular { get; set; } = string.Empty;

        [EmailAddress]
        [StringLength(40)]
        public string Correo { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime FechaDeIngreso { get; set; }

        [StringLength(50)]
        public string Profesión { get; set; } = string.Empty;

        [StringLength(50)]
        public string Puesto { get; set; } = string.Empty;

        [DataType(DataType.Currency)]
        public double Salario { get; set; }
    }
}

Clientes/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clientes.Models;

namespace Clientes.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly ClientesContext _context;

        public EmpleadoController(ClientesContext context)
        {
            _context = context;
        }

        // GET: Empleado
       // public async Task<IActionResult> Index()
       // {
      //      return View(await _context.Empleados.ToListAsync());
      //  }

        // GET: Empleado/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleado/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleado/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Cedula,Nombres,Apellidos,FechaDeNacimiento,Departamento,Municipio,Dirección,Teléfono,Celular,Correo,FechaDeIngreso,Profesión,Puesto,Salario")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleado/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleado/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cedula,Nombres,Apellidos,FechaDeNacimiento,Departamento,Municipio,Dirección,Teléfono,Celular,Correo,FechaDeIngreso,Profesión,Puesto,Salario")] Empleado empleado)
        {
            if (id != empleado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleado/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado != null)
            {
                _context.Empleados.Remove(empleado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleados.Any(e => e.Id == id);
        }


       // GET: Empleado
    public async Task<IActionResult> Index(string searchString)
    {
        if (!String.IsNullOrEmpty(searchString))
        {
            var empleados = await _context.GetEmpleadosByNombre(searchString);
            return View(empleados);
        }
        return View(await _context.Empleados.ToListAsync());
    }
        
    }
}

Clientes/Views/Empleado/Create.cshtml
@model Empleado

@{
    ViewData["Title"] = "Crear";
}

<h1>Create</h1>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <input asp-for="Departamento" class="form-control" />
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Municipio" class="control-label"></label>
                <input asp-for="Municipio" class="form-control" />
                <span asp-validation-for="Municipio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dirección" class="control-label"></label>
                <input asp-for="Dirección" class="form-control" />
                <span asp-validation-for="Dirección" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Teléfono" class="control-label"></label>
                <input asp-for="Teléfono" class="form-control" />
                <span asp-validation-for="Teléfono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeIngreso" class="control-label"></label>
                <input asp-for="FechaDeIngreso" class="form-control" />
                <span asp-validation-for="FechaDeIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profesión" class="control-label"></label>
                <input asp-for="Profesión" class="form-control" />
                <span asp-validation-for="Profesión" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puesto" class="control-label"></label>
                <input asp-for="Puesto" class="form-control" />
                <span asp-validation-for="Puesto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clientes/Views/Empleado/Delete.cshtml
@model Empleado

@{
    ViewData["Title"] = "Borrar";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDeNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Municipio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dirección)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dirección)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teléfono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teléfono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDeIngreso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Profesión)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profesión)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Puesto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Puesto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Clientes/Views/Empleado/Details.cshtml
@model Empleado

@{
    ViewData["Title"] = "Actualizar";
}

<h1>Details</h1>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDeNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Municipio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dirección)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dirección)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teléfono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teléfono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDeIngreso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Profesión)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profesión)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Puesto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Puesto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Clientes/Views/Empleado/Edit.cshtml
@model Empleado

@{
    ViewData["Title"] = "Actualizar";
}

<h1>Edit</h1>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <input asp-for="Departamento" class="form-control" />
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Municipio" class="control-label"></label>
                <input asp-for="Municipio" class="form-control" />
                <span asp-validation-for="Municipio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dirección" class="control-label"></label>
                <input asp-for="Dirección" class="form-control" />
                <span asp-validation-for="Dirección" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Teléfono" class="control-label"></label>
                <input asp-for="Teléfono" class="form-control" />
                <span asp-validation-for="Teléfono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeIngreso" class="control-label"></label>
                <input asp-for="FechaDeIngreso" class="form-control" />
                <span asp-validation-for="FechaDeIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profesión" class="control-label"></label>
                <input asp-for="Profesión" class="form-control" />
                <span asp-validation-for="Profesión" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puesto" class="control-label"></label>
                <input asp-for="Puesto" class="form-control" />
                <span asp-validation-for="Puesto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clientes/Views/Empleado/Index.cshtml
@model IEnumerable<Empleado>

@{
    ViewData["Title"] = "Empleados";
}


<div class="container mt-4">
    <h1 class="mb-4">Lista de Empleados</h1>

    <div class="row mb-3">
        <div class="col-md-6">
            <form asp-controller="Empleado" asp-action="Index" method="get" class="form-inline">
                <div class="input-group">
                    <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" class="form-control" placeholder="Buscar por nombre..." />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-success">Buscar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-6 text-right">
            <a class="btn btn-secondary btn-sm" asp-action="Create">Crear Nuevo Empleado</a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th>Cedula</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha de Nacimiento</th>
                    <th>Departamento</th>
                    <th>Municipio</th>
                    <th>Dirección</th>
                    <th>Teléfono</th>
                    <th>Celular</th>
                    <th>Correo</th>
                    <th>Fecha de Ingreso</th>
                    <th>Profesión</th>
                    <th>Puesto</th>
                    <th>Salario</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Cedula)</td>
                        <td>@Html.DisplayFor(modelItem => item.Nombres)</td>
                        <td>@Html.DisplayFor(modelItem => item.Apellidos)</td>
                        <td>@Html.DisplayFor(modelItem => item.FechaDeNacimiento)</td>
                        <td>@Html.DisplayFor(modelItem => item.Departamento)</td>
                        <td>@Html.DisplayFor(modelItem => item.Municipio)</td>
                        <td>@Html.DisplayFor(modelItem => item.Dirección)</td>
                        <td>@Html.DisplayFor(modelItem => item.Teléfono)</td>
                        <td>@Html.DisplayFor(modelItem => item.Celular)</td>
                        <td>@Html.DisplayFor(modelItem => item.Correo)</td>
                        <td>@Html.DisplayFor(modelItem => item.FechaDeIngreso)</td>
                        <td>@Html.DisplayFor(modelItem => item.Profesión)</td>
                        <td>@Html.DisplayFor(modelItem => item.Puesto)</td>
                        <td>@Html.DisplayFor(modelItem => item.Salario)</td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group">
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                                <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Detalles</a>
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                                <button class="btn btn-secondary" onclick="imprimirDetalle()">Imprimir</button> <!-- Botón de imprimir -->
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<style>
    .table {
        font-size: 0.875rem;
    }
    .thead-light th {
        text-align: center;
    }
    .btn-sm {
        padding: 0.25rem 0.5rem;
        font-size: 0.75rem;
    }
    .btn-group-sm .btn {
        font-size: 0.75rem;
    }
</style>

<script>
    function imprimirDetalle() {
        window.print();
    }
</script>